# Generated by Django 6.1.1 on 2026-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('logo', models.CharField(blank=True, max_length=255)),
                ('informacion', models.TextField(blank=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'Escudería',
                'verbose_name_plural': 'Escuderías',
                'ordering': ['nombre'],
            },
        ),
    ]
