# Generated by Django 6.1.1 on 2026-10-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuderias', '0001_initial'),
        ('pilotos', '0002_piloto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionPiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('escuderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='escuderias.escuderia')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='pilotos.piloto')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='pilotos.temporada')),
            ],
            options={
                'verbose_name': 'Participación de piloto',
                'verbose_name_plural': 'Participaciones de pilotos',
                'ordering': ['temporada', 'piloto'],
                'constraints': [models.UniqueConstraint(fields=('temporada', 'piloto'), name='piloto_unico_por_temporada')],
            },
        ),
    ]
